apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    # your IAM identity for kubectl access:
    - userarn: arn:aws:iam::575108955979:user/genfied-deployer
      username: genfied-deployer
      groups:
        - system:masters

  mapAccounts: |
    # allow any IAM entity in your AWS account (optional)
    - 575108955979

  mapRoles: |
    # self‑managed node group role (only)
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::575108955979:role/AmazonEKSNodeSelfManagedRole
      username: system:node:{{EC2PrivateDNSName}}
