apiVersion: v1
kind: ConfigMap
metadata:
  name: reid-env-config
  namespace: genfied
data:
  AUTH_REFRESH_INTERVAL: "1800"
  AUTH_USERNAME: "admin"
  AUTH_PASSWORD: "admin123"
  AUTH_ENDPOINT: "http://genfied-api.xperie.nz:8000/api/v1/auth/login"
  KAFKA_BOOTSTRAP_SERVERS: "4.232.129.207:29092"
  KAFKA_CONSUMER_GROUP: "reid-processor"
  KAFKA_TOPIC_PATTERN: "^store-([0-9]+)$"
  MILVUS_ROUTER_URL: "http://milvus-router.genfied.svc.cluster.local"
  MILVUS_BATCH_SIZE: "50"
  MILVUS_BATCH_INTERVAL: "0.3"
  MILVUS_MAX_CONCURRENT: "300"
  MILVUS_MIN_INTERVAL: "0.001"
  MILVUS_ENABLE_RATE_LIMITING: "false"
  MILVUS_ENABLE_SEMAPHORE: "true"
