apiVersion: v1
data:
  config_service_url: ""
  redis_url: ""
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config_service_url":"","redis_url":""},"kind":"ConfigMap","metadata":{"annotations":{},"name":"milvus-router-config","namespace":"genfied"}}
  creationTimestamp: "2025-05-18T17:34:07Z"
  name: milvus-router-config
  namespace: genfied
  resourceVersion: "11199873"
  uid: e15eb419-bf3a-473f-a808-118ba1f9f5ba
